version: '2'
services:
    albums:
        image: glennc/musicstore-albums
        ports:
            - 5000
        environment:
            - Data__DefaultConnection__ConnectionString=<connStr>
    web:
        image: glennc/musicstore-web
        ports:
            - 80:5000
        environment:
            - AppSettings__AlbumsUrl=http://musicstore_albums:5000
